apiVersion: apps/v1
kind: Deployment
metadata:
  name: growth-backend
spec:
  replicas: 2
  selector:
    matchLabels:
      app: growth-backend
  template:
    metadata:
      labels:
        app: growth-backend
    spec:
      containers:
      - name: growth-backend
        image: muhammadhassaan43/web_project:backend
        ports:
        - containerPort: 5000
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: growth-frontend
spec:
  replicas: 2
  selector:
    matchLabels:
      app: growth-frontend
  template:
    metadata:
      labels:
        app: growth-frontend
    spec:
      containers:
      - name: growth-frontend
        image: muhammadhassaan43/web_project:frontend
        ports:
        - containerPort: 80
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: growth-mongo
spec:
  replicas: 1
  selector:
    matchLabels:
      app: growth-mongo
  template:
    metadata:
      labels:
        app: growth-mongo
    spec:
      containers:
      - name: growth-mongo
        image: mongo:latest
        ports:
        - containerPort: 27017
        env:
        - name: MONGO_INITDB_ROOT_USERNAME
          value: root
        - name: MONGO_INITDB_ROOT_PASSWORD
          value: example
