apiVersion: v1
kind: Service
metadata:
  name: growth-backend-service
spec:
  type: NodePort
  selector:
    app: growth-backend
  ports:
    - port: 80
      targetPort: 5000
      nodePort: 30007
---
apiVersion: v1
kind: Service
metadata:
  name: growth-frontend-service
spec:
  type: NodePort
  selector:
    app: growth-frontend
  ports:
    - port: 80
      targetPort: 80
      nodePort: 30008
---
apiVersion: v1
kind: Service
metadata:
  name: growth-mongo-service
spec:
  type: ClusterIP
  selector:
    app: growth-mongo
  ports:
    - port: 27017
      targetPort: 27017
